CREATE TABLE categories (
    category_id INT PRIMARY KEY,
    name ENUM('MOVIES','EDUCATIONAL','CARS','OTHER'), 
    description TEXT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);