CREATE TABLE event_images (
    image_id VARCHAR(100) PRIMARY KEY,
    event_id VARCHAR(255) ,
    image_url VARCHAR(255),
    FOREIGN KEY (event_id) REFERENCES events(event_id),
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);