CREATE TABLE statuses (
    status_id INT PRIMARY KEY,
    name ENUM('APPROVED','PUBLISHED','CANCELLED','PENDING'), 
    description TEXT,
    created_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated_on TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);